# Generated by Django 4.0 on 2022-01-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsisizPersonel',
            fields=[
                ('tc', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('ad', models.CharField(max_length=30)),
                ('soyad', models.CharField(max_length=30)),
                ('covid_t', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'db_table': 'asisiz_personel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AsisizPersonelHastalikReceteBilgisi',
            fields=[
                ('h_isim', models.CharField(max_length=30)),
                ('recete_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'asisiz_personel_hastalik',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BelirliBirILaciKullananlarCovid',
            fields=[
                ('tc', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('ad', models.CharField(max_length=30)),
                ('soyad', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'belirli_bir_ilaci_kullananlar_covid',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BelirliBirIlacKullananlar',
            fields=[
                ('tc', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('ad', models.CharField(max_length=30)),
                ('soyad', models.CharField(max_length=30)),
                ('ilac', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'belirli_bir_ilaci_kullananlar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BelirliKronikHastalikCovidSuresi',
            fields=[
                ('kronik_hastalik', models.CharField(max_length=60)),
                ('gun_sayisi', models.DecimalField(decimal_places=0, max_digits=12, primary_key=True, serialize=False)),
                ('hasta_sayisi', models.BigIntegerField()),
            ],
            options={
                'db_table': 'belirli_kronik_hastalik_covid_suresi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BiontechBelirliHastalikCovid',
            fields=[
                ('tc', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('ad', models.CharField(max_length=30)),
                ('soyad', models.CharField(max_length=30)),
                ('hastalik', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'biontech_belirli_hastalik_covid',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BiontechCovidliPer',
            fields=[
                ('toplam_sure', models.DecimalField(decimal_places=2, max_digits=6, primary_key=True, serialize=False)),
                ('per_sayisi', models.BigIntegerField()),
            ],
            options={
                'db_table': 'biontech_covidli_per',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CovidPerMesaiSaatDurumu',
            fields=[
                ('haftalik_saat', models.DecimalField(decimal_places=2, max_digits=5, primary_key=True, serialize=False)),
                ('per_sayisi', models.BigIntegerField()),
            ],
            options={
                'db_table': 'covid_per_mesai_saat_durumu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EgitimCovid',
            fields=[
                ('egitim_seviyesi', models.CharField(choices=[('lisans', 'lisans'), ('yükseklisans', 'yükseklisans'), ('doktora', 'doktora')], max_length=30, primary_key=True, serialize=False)),
                ('sayim', models.BigIntegerField()),
            ],
            options={
                'db_table': 'egitim_covid',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EnSkHastaPersonel',
            fields=[
                ('per_id', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('hastalik_say', models.BigIntegerField()),
            ],
            options={
                'db_table': 'en_sk_hasta_per',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EnSkHastaPersonelCovid',
            fields=[
                ('tc', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('ad', models.CharField(max_length=30)),
                ('soyad', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'en_sk_hasta_per_covid',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EnTemasliInsanlar',
            fields=[
                ('tc', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('ad', models.CharField(max_length=30)),
                ('soyad', models.CharField(max_length=30)),
                ('temas_say', models.BigIntegerField()),
            ],
            options={
                'db_table': 'en_temasli_insanlar_listesi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EnYayginCovidSemptomlari',
            fields=[
                ('semptom', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('semptom_say', models.BigIntegerField()),
            ],
            options={
                'db_table': 'en_yaygin_covid_semptomlari',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EnYayginHastaliklar',
            fields=[
                ('h_isim', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('hastalik_sayisi', models.BigIntegerField()),
            ],
            options={
                'db_table': 'en_yaygin_hastaliklar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EnYayginHastalikPer',
            fields=[
                ('tc', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('ad', models.CharField(max_length=30)),
                ('soyad', models.CharField(max_length=30)),
                ('h_isim', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'en_yaygin_hastaliklar_per',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EnYayginIlacKullananlar',
            fields=[
                ('tc', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('ad', models.CharField(max_length=32)),
                ('soyad', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'en_yaygin_ilac_kullananlar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EnYayginIlaclar',
            fields=[
                ('ilac_isim', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('ilac_sayim', models.BigIntegerField()),
            ],
            options={
                'db_table': 'en_yaygin_ilaclar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HaftasonuPersonel',
            fields=[
                ('tc', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('ad', models.CharField(max_length=30)),
                ('soyad', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'haftasonu_per',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HaftasonuPersonelCovid',
            fields=[
                ('tc', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('ad', models.CharField(max_length=30)),
                ('soyad', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'haftasonu_per_covid',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KanGrubuCovidSklk',
            fields=[
                ('kan_grubu', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('covid_sklk', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
            options={
                'db_table': 'kan_grubu_covid_sklk',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SehirYayginHastaliklar',
            fields=[
                ('sehir', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('h_isim', models.CharField(max_length=30)),
                ('hastalik_sayisi', models.BigIntegerField()),
            ],
            options={
                'db_table': 'sehir_yaygin_hastaliklar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SinovacCovidliPer',
            fields=[
                ('toplam_sure', models.DecimalField(decimal_places=2, max_digits=6, primary_key=True, serialize=False)),
                ('per_sayisi', models.BigIntegerField()),
            ],
            options={
                'db_table': 'sinovac_covidli-per',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='personel',
            name='posizyon',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
