# Generated by Django 4.0 on 2022-01-01 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_asisizpersonel_asisizpersonelhastalikrecetebilgisi_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sinovaccovidliper',
            table='sinovac_covidli_per',
        ),
    ]
