# Generated by Django 4.0 on 2022-01-02 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_sinovaccovidliper_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temaslikisiler',
            name='pers',
        ),
        migrations.AddField(
            model_name='temaslikisiler',
            name='per',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='company.personel'),
            preserve_default=False,
        ),
    ]
