# Generated by Django 4.0 on 2022-01-02 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_remove_temaslikisiler_pers_temaslikisiler_per'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temaslikisiler',
            name='per',
        ),
        migrations.AddField(
            model_name='temaslikisiler',
            name='pers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.personel'),
        ),
    ]
