# Generated by Django 4.0 on 2022-01-02 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_remove_temaslikisiler_per_temaslikisiler_pers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TemasliKisiler',
            new_name='TemasliKisi',
        ),
    ]
