# Generated by Django 4.0 on 2022-01-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_rename_temaslikisiler_temaslikisi'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemasliKisiler',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pers', models.CharField(max_length=60)),
            ],
        ),
    ]
