# Generated by Django 4.0 on 2022-01-03 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_alter_entemasliinsanlar_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='BelirliSehirHastalik',
            fields=[
                ('ad', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('soyad', models.CharField(max_length=30)),
                ('sehir', models.CharField(max_length=60)),
                ('h_isim', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'belirli_sehir_hastalik',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='SehirYayginHastaliklar',
        ),
    ]
