# Generated by Django 3.0.5 on 2022-05-09 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_belirlisehirhastalik_delete_sehiryayginhastaliklar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TemasliKisiler',
        ),
        migrations.AlterField(
            model_name='mesai',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
