# Generated by Django 3.0.5 on 2022-05-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_auto_20220509_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personel',
            name='egitim_seviyesi',
            field=models.CharField(choices=[('Lisans', 'Lisans'), ('Yükseklisans', 'Yükseklisans'), ('Doktora', 'Doktora')], max_length=30),
        ),
    ]
