# Generated by Django 3.0.5 on 2022-05-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_auto_20220513_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personel',
            name='egitim_seviyesi',
            field=models.CharField(choices=[('Lisans', 'Lisans'), ('yükseklisans', 'yükseklisans'), ('doktora', 'doktora')], max_length=30),
        ),
    ]
